version: 0.2

phases:
  build:
    commands:
      - echo "Building website..."
  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync . s3://my-first-website-saivenkat --delete --exclude ".git/*" --exclude "buildspec.yml"
      - echo "Done!"

artifacts:
  files:
    - '**/*'
